FROM python:3.4-jessie

RUN mkdir -p /opt/site
WORKDIR /opt/site

# install pelican-ipynb
RUN mkdir plugins
RUN git clone git://github.com/danielfrg/pelican-ipynb.git plugins/ipynb

RUN pip install --upgrade pip && \
    pip install -r plugins/ipynb/requirements.txt

RUN mkdir content

COPY pelicanconf.py .

CMD /bin/bash
